[package]
name = "viewr-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rawler.workspace = true
rayon.workspace = true
thiserror.workspace = true
image.workspace = true
fast_image_resize.workspace = true
jpeg-encoder.workspace = true
zune-jpeg.workspace = true
